version: '2'
services:
  db:
    image: 'mysql:8.0.3'
    restart: always
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kanboard
      - MYSQL_USER=kanboard
      - MYSQL_PASSWORD=kanboard
    volumes:
      - db:/var/lib/mysql

  web:
<<<<<<< HEAD
    image: kanboard/kanboard:latest
=======
    build: .
>>>>>>> d6764de50a58b74a0aa16c4f1473e7269501cc43
    restart: always
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
      - kanboard_ssl:/etc/nginx/ssl
    environment:
      DATABASE_URL: mysql://kanboard:kanboard@db/kanboard
    depends_on:
      - db
volumes:
  kanboard_data:
  kanboard_plugins:
  kanboard_ssl:
  db:
