version: '2'
services:
  web:
    image: kanboard/kanboard:latest
    restart: always
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
    environment:
      DATABASE_URL: mysql://kanboard:kanboard@host.docker.internal/kanboard_db # Cambia "host.docker.internal" por "localhost" si es el mismo servidor
volumes:
  kanboard_data:
  kanboard_plugins: